rayo/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

app_name = "rayo"

urlpatterns = [
    path('penhoon/', admin.site.urls),
    # path('' , views.home),
    path('' , include("shop.urls")),
    path('users/', include("users.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # path('', views.users, name='users'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
    # path('profile/<slug>', views.profile, name='profile'),
    # path('follow/<slug>', views.follow_view, name='follow')
]

users/models.py
from django.db import models
# from django.contrib.auth.models import User


class Profile(models.Model):
    name = models.CharField(max_length=150)
    # bio = models.CharField(max_length=250)
    user_slug = models.SlugField(default=None)

    def __str__(self):
        return str(self.name)


# class Follow(models.Model):
#     me = models.OneToOneField(User, on_delete=models.CASCADE, related_name="me")
#     other_guy = models.ManyToManyField(User, blank=True, related_name='other_guy')
#     follower_slug = models.SlugField(default=str(me).strip())
#     is_following = models.BooleanField(default=False)

#     def __str__(self):
#         return str(self.me)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


# class CreateProfile(forms.ModelForm):
#     class Meta():
#         model = models.Profile
#         fields = []

class CreateProfile(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


# class Follow_form(forms.ModelForm):
#     class Meta():
#         model = models.Follow
#         fields = []

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# from posts.models import Post
from .models import Profile
from .forms import CreateProfile
from django.contrib.auth.decorators import login_required


# @login_required(login_url='/users/login')
# def users(request):
#     return render(request, 'usersPage.html')


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return render(request, 'signup.html', {'form': form})
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        # form2 = CreateProfile(request.POST)
        if form.is_valid():
            user = form.save()
            s = request.POST.dict()
            # instance = form2.save(commit=False)
            iname = s['username']
            # instance.name = str(s.username)
            # instance.user_slug = str(instance.name).strip()
            instance = Profile(name=iname , user_slug=iname.strip())
            instance.save()
            login(request, user)
            # return redirect('shop')
            return render(request, 'signup.html', {'form': form})
            
    form = CreateProfile()
    return render(request, 'signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('shop')


# @login_required(login_url='/users/login')
# def profile(request, slug):
#     posts = Post.objects.all()
#     form = Profile.objects.get(user_slug=slug)
#     our_name = str(Profile.objects.get(name=request.user))
#     is_following = bool(Follow.is_following)
#     return render(request, 'profile.html',
#                   {'form': form, 'posts': posts, 'our_name': our_name, 'is_following': is_following})

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    SignUp
</title>
</head>

<div class="wrapper">


<body>
    <h1>Login</h1>
<form class="site-form" method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input name="next" type="hidden" value="{{ request.GET.next }}">
        {% endif %}
    <input type="submit" value="Log Me In" class="input1">

<div class="signup_request"><p>dont have any account? <a href="{% url 'users:signup' %}">create one</a></p></div>
</form>

</body>
</div>
</html>

users/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    ProfilePage
{% endblock %}

{% block body %}
    <h1 class="profile_name">///&nbsp;&nbsp;&nbsp; {{ form.name }} &nbsp;&nbsp;&nbsp; ///</h1>
    {% if our_name != form.name and form.name != 'sinarayo' %}
        <h1>{{ is_following }}</h1>
        {% if is_following == False %}
            <a href="{% url "users:follow" slug=form.name %}" class="follow_btn">Follow</a>
        {% elif is_following == True %}
            <a href="{% url "users:follow" slug=form.name %}" class="Unfollow_btn">unFollow</a>
        {% endif %}

    {% elif our_name == form.name %}
        <h1 class="follow_btn">Your Profile</h1>
    {% elif form.name == 'sinarayo' %}
        <h1 class="follow_btn">Admin</h1>
    {% endif %}
    <h1>Posts</h1>

    {% for post in posts %}
        {% if post.author.username == form.name %}
            <div class="article">
                <h2 class="post_title"><a href="{% url 'posts:post_detail' slug=post.slug %}"> {{ post.title }} </a>
                </h2>
                <p class="editedbody"> {{ post.editedbody }} </p>
             {% if post.author.username == our_name %}
                <p><a href="{% url 'posts:delete' slug=post.slug %}">delete post</a></p>
             {% endif %}
            </div>
        {% endif %}
    {% endfor %}

{% endblock %}

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    SignUp
</title>
</head>

<div class="wrapper">


<body>
    <h1>Sign Up</h1>
<form class="site-form" method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {{ form }}
    
    <input type="submit" value="Sign Me Up" class="input1">
<div class="signup_request"><p>already have an account?  <a href="{% url 'users:login' %}">login</a></p></div>
</form>

</body>
</div>
</html>

users/templates/usersPage.html
{% extends 'base.html' %}

{% block title %}
UsersPage
{% endblock %}
{% block body %}
    <nav>
    <ul>
        <li>
            <form class="logout-list" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
        </li>
    </ul>
</nav>


<h2><a href="{% url 'users:signup' %}"> Create Your account </a></h2>

<p> Do you have one? </p>
<h2><a href="{% url 'users:login' %}">Log in</a></h2>
{% endblock %}